[package]
name = "common-storage"
version = "0.1.0"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[features]
storage-hdfs = ["opendal/services-hdfs"]

[dependencies]
common-base = { path = "../base" }
common-contexts = { path = "../contexts" }
common-exception = { path = "../exception" }

anyhow = "1.0.58"
backon = "0.0.2"
globiter = "0.1.0"
once_cell = "1.12.0"
opendal = { version = "0.14.1", features = [
    "layers-retry",
    "services-http",
    "layers-tracing",
    "layers-metrics",
    "compress",
] }
percent-encoding = "2.1.0"
serde = { version = "1.0.137", features = ["derive"] }
