[package]
name = "common-pipeline-sources"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
doctest = false
test = false

[dependencies]
common-base = { path = "../../../common/base" }
common-catalog = { path = "../../catalog" }
common-datablocks = { path = "../../datablocks" }
common-exception = { path = "../../../common/exception" }
common-formats = { path = "../../formats" }
common-io = { path = "../../../common/io" }
common-meta-types = { path = "../../../meta/types" }
common-pipeline-core = { path = "../core" }
common-storage = { path = "../../../common/storage" }
common-streams = { path = "../../streams" }

async-trait = { version = "0.1.0", package = "async-trait-fn" }
futures = "0.3.21"
futures-util = "0.3.21"
opendal = { version = "0.14.1", features = ["layers-retry", "compress"] }
parking_lot = "0.12.1"
